### ISSUE TITLE
[2] Fix and test eosjs transfer

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/beet#92]
See #91

To test the transfer open the corresponding example in beet-js while running beet.
https://github.com/bitshares/beet-js/blob/90b8ad8eb472af96ab59fc48e5785c9844343180/examples/transfer/eos.html#L4

The code in beet is found here:
https://github.com/bitshares/beet/blob/dd3ea27669306f52a6bd5f75e24e9e99d973d139/src/lib/blockchains/EOSmainnet.js#L152

I want to be able to support the transfer of any EOSIO token, and the action I implemented is probably wrong and only for EOS.

**Comment by clockworkgr** [comment]
eosio token contract....

**Comment by clockworkgr** [comment]
https://eosio.stackexchange.com/questions/3610/how-to-transfer-eos-token-with-eosjs

**Comment by Kennybll** [comment]
When I test the EOSjs code, with the beet-js example transfer script, beet's UI crashes. I can link my EOS account, and I press the transfer button, but after a few seconds, the whole UI just disappears. The process is still running, I even try to have the console open, which doesn't show anything, and if I open the console window after the crash (ctrl+shift+i) it says it can't connect to the window. I haven't been able to find the source of the crash. I've used VS Code's debugger and some console.log's but couldn't find it, maybe someone else will have more luck. Stefan said to write down my hours, which was 3 hours. It took around 30 minutes to figure out the right import through the docs and testing. It took 2.5 hours of testing to find the crash. But since I couldn't find it, I figured may as well let someone else try before I spend more time on it.
